export interface User {
    id: string,
    email: string,
    password: string,
    firstName: string,
    lastName: string,
    role: "STUDENT" | "ADMIN",
    studentId: string | null,
    phone: string | null,
    address: string | null,
    dateOfBirth: Date | null,
    registeredAt: Date,
    isActive: boolean,
    refreshToken: string | null,
}
